// mockData.ts
import { DBResourceItem } from './types'
export const getMockDetailsData = () => ({
    id: 1,
    envId: 10,
    envName: '环境标11',
    softAppId: '202020200202020202',
    softAppCode: 'APAAS.ADM',
    softAppCnName: 'APAAS.ADM',
    softAppEnName: 'datacenter',
    logicalDeploymentArchitectureId: 0,
    verLogicalDeploymentArchitectureId: 1110,
    compDeploymentList: [
        {
            path: '全行/Region/AZ/LDC1/SR/CZ1',
            groupList: [
                {
                    groupName: 'NOMAL',
                    componentName: 'Test001',
                    componentVersion: '1.2.0',
                    compSpecCPU: '2核',
                    compSpecMemory: '4G',
                    compSpecInstanceNum: '2',
                    hostOSName: '麒麟',
                    hostOSVersion: 'v2.0',
                    hostCPU: '4核',
                    hostMemory: '8G',
                    hostInstanceNum: 2,
                    hostFileSystemList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            user: '/user1',
                            group: 'zhuzu',
                            mount: '/src/user',
                            size: '10G',
                        },
                        {
                            id: 10,
                            hostSpecId: 0,
                            user: '/user2',
                            group: 'group',
                            mount: '/src/user',
                            size: '10G',
                        },
                    ],
                    hostSoftwareList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            name: 'tomcat',
                            version: '7.8',
                            type: '客户端',
                            remark: '备注备注备注备注备注备注',
                        },
                    ],
                },
                {
                    groupName: 'NOMAL',
                    componentName: 'Test002',
                    componentVersion: '1.2.0',
                    compSpecCPU: '2核',
                    compSpecMemory: '4G',
                    compSpecInstanceNum: '2',
                    hostOSName: '麒麟',
                    hostOSVersion: 'v2.0',
                    hostCPU: '4核',
                    hostMemory: '8G',
                    hostInstanceNum: 2,
                    hostFileSystemList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            user: '/user1',
                            group: 'zhuzu',
                            mount: '/src/user',
                            size: '10G',
                        },
                        {
                            id: 10,
                            hostSpecId: 0,
                            user: '/user2',
                            group: 'group',
                            mount: '/src/user',
                            size: '10G',
                        },
                    ],
                    hostSoftwareList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            name: 'tomcat',
                            version: '7.8',
                            type: '客户端',
                            remark: '备注备注备注备注备注备注',
                        },
                    ],
                },
                {
                    groupName: 'GRAY',
                    componentName: 'Test001',
                    componentVersion: '1.2.0',
                    compSpecCPU: '2核',
                    compSpecMemory: '4G',
                    compSpecInstanceNum: '2',
                    hostOSName: '麒麟',
                    hostOSVersion: 'v2.0',
                    hostCPU: '4核',
                    hostMemory: '8G',
                    hostInstanceNum: 2,
                    hostFileSystemList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            user: '/user1',
                            group: 'zhuzu',
                            mount: '/src/user',
                            size: '10G',
                        },
                        {
                            id: 10,
                            hostSpecId: 0,
                            user: '/user2',
                            group: 'group',
                            mount: '/src/user',
                            size: '10G',
                        },
                    ],
                    hostSoftwareList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            name: 'tomcat',
                            version: '7.8',
                            type: '客户端',
                            remark: '备注备注备注备注备注备注',
                        },
                    ],
                },
            ],
        },
        {
            path: '全行/Region/AZ/LDC2/SR/CZ2',
            groupList: [
                {
                    groupName: 'NOMAL',
                    componentName: 'APAAS.AUTH.service001',
                    componentVersion: '1.2.0',
                    compSpecCPU: '2核',
                    compSpecMemory: '4G',
                    compSpecInstanceNum: '2',
                    hostOSName: '麒麟',
                    hostOSVersion: 'v2.0',
                    hostCPU: '4核',
                    hostMemory: '8G',
                    hostInstanceNum: 3,
                    hostFileSystemList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            user: '/user1',
                            group: 'zhuzu',
                            mount: '/src/user',
                            size: '10G',
                        },
                        {
                            id: 10,
                            hostSpecId: 0,
                            user: '/user2',
                            group: 'group',
                            mount: '/src/user',
                            size: '10G',
                        },
                    ],
                    hostSoftwareList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            name: 'tomcat',
                            version: '7.8',
                            type: '客户端',
                            remark: '备注备注备注备注备注备注备注',
                        },
                    ],
                },
                {
                    groupName: 'NOMAL',
                    componentName: 'APAAS.AUTH.service002',
                    componentVersion: '1.2.0',
                    compSpecCPU: '2核',
                    compSpecMemory: '4G',
                    compSpecInstanceNum: '2',
                    hostOSName: '麒麟',
                    hostOSVersion: 'v2.0',
                    hostCPU: '4核',
                    hostMemory: '8G',
                    hostInstanceNum: 2,
                    hostFileSystemList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            user: '/user1',
                            group: 'zhuzu',
                            mount: '/src/user',
                            size: '10G',
                        },
                        {
                            id: 10,
                            hostSpecId: 0,
                            user: '/user2',
                            group: 'group',
                            mount: '/src/user',
                            size: '10G',
                        },
                    ],
                    hostSoftwareList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            name: 'tomcat',
                            version: '7.8',
                            type: '客户端',
                            remark: '备注备注备注备注备注备注备注备注',
                        },
                    ],
                },
            ],
        },
    ],
    dbTypeList: [
        {
            dbType: 'TDSQL',
            dbSpecList: [
                {
                    path: '全行/Region/AZ/LDC/SR/CZ9',
                    specList: [
                        {
                            dbVersion: '7.0',
                            osSystem: 'Windows',
                            instanceName: 'instanceName990',
                            instanceNum: 3,
                            otherSpecList: [
                                {
                                    id: '1',
                                    dbName: 'db001',
                                    schemaName: 'schema001',
                                    shardingMethod: 'shardingMethod001',
                                    tablespaceName: 'tablespaceName001',
                                    tablespaceSize: '10GB',
                                    charset: 'dd',
                                    userName: 'userName001',
                                },
                                {
                                    id: '2',
                                    dbName: 'db002',
                                    schemaName: 'schema002',
                                    shardingMethod: 'shardingMethod002',
                                    tablespaceName: 'tablespaceName002',
                                    tablespaceSize: '10GB',
                                    charset: 'dd',
                                    userName: 'userName002',
                                },
                            ],
                        },
                        {
                            dbVersion: '7.1',
                            osSystem: 'Windows',
                            instanceName: 'instanceName991',
                            instanceNum: 2,
                            otherSpecList: [
                                {
                                    id: '1',
                                    dbName: 'db001',
                                    schemaName: 'schema001',
                                    shardingMethod: 'shardingMethod001',
                                    tablespaceName: 'tablespaceName001',
                                    tablespaceSize: '10GB',
                                    charset: 'dd',
                                    userName: 'userName001',
                                },
                                {
                                    id: '2',
                                    dbName: 'db002',
                                    schemaName: 'schema002',
                                    shardingMethod: 'shardingMethod002',
                                    tablespaceName: 'tablespaceName002',
                                    tablespaceSize: '10GB',
                                    charset: 'dd',
                                    userName: 'userName002',
                                },
                            ],
                        },
                    ],
                },
                {
                    path: '全行/Region/AZ/LDC/SR/CZ10',
                    specList: [
                        {
                            dbVersion: '7.0',
                            osSystem: 'Windows',
                            instanceName: 'instanceName',
                            instanceNum: 3,
                            otherSpecList: [
                                {
                                    id: '1',
                                    dbName: 'db001',
                                    schemaName: 'schema001',
                                    shardingMethod: 'shardingMethod001',
                                    tablespaceName: 'tablespaceName001',
                                    tablespaceSize: '10GB',
                                    charset: 'dd',
                                    userName: 'userName001',
                                },
                                {
                                    id: '2',
                                    dbName: 'db002',
                                    schemaName: 'schema002',
                                    shardingMethod: 'shardingMethod002',
                                    tablespaceName: 'tablespaceName002',
                                    tablespaceSize: '10GB',
                                    charset: 'dd',
                                    userName: 'userName002',
                                },
                            ],
                        },
                    ],
                },
            ],
        },
    ],
})

// 已选择的资源数据
export const getMockHostResourceItems = () => [
    {
        id: '11',
        name: 'host001',
        ipAddress: '12.22.111',
        memoryGb: '8G',
        cpuModel: '4G',
        hostOSName: '麒麟',
        hostOSVersion: 'v2.0',
        fileSystems: [
            {
                id: 0,
                mountPoint: '9.0',
                sizeGb: '10GB',
                username: '/user01',
                groupName: '主组',
            },
            {
                id: 10,
                mountPoint: '1.0',
                sizeGb: '12GB',
                username: 'user02',
                groupName: 'groupName',
            },
        ],
        installedSoftwares: [
            {
                id: 0,
                softwareName: 'sd',
                version: '2.1',
                type: '中间件',
                remark: '备注备注备注备注备注',
            },
        ],
        mappingId: '12.22.111-mappingId1', // 映射id
        verLogicalDeploymentArchId: '21212220',
    },
]

export const getMockDBResources = (): any[] => [
    {
        id: '11',
        envId: '1222222333331',
        envName: '',
        softAppId: '1222222333344431',
        softAppCode: '',
        isDeleted: 0,
        createTime: '',
        updateTime: '',
        ip: '12.12.15',
        port: '9091',
        dbType: '',
        version: '2C',
        instanceName: 'we',
        hostOSName: '操作系统',
        hostOSVersion: 'v2.0',
        status: 0,
        envResourceId: '12222',
        databaseResourceList: [
            {
                id: '122222',
                serviceId: '2333',
                dbName: 'tb_user001',
                charset: 'UTF8',
                userName: '用户名',
                tablespaceName: 'apaasadm',
                tablespaceSize: '40GB',
                shardingMethod: '负载均衡',
                isDeleted: 0,
                createTime: '',
                updateTime: '',
            },
        ],
        selectedFlag: false,
        mappingId: '12.12.15-mappingId3',
        verLogicalDeploymentArchId: '12122',
        relationId: 'relationId3',
    },
    {
        id: '12',
        envId: '1222222333331',
        envName: '',
        softAppId: '1222222333344431',
        softAppCode: '',
        isDeleted: 0,
        createTime: '',
        updateTime: '',
        ip: '12.12.16',
        port: '9091',
        dbType: '',
        version: '2C',
        instanceName: 'we',
        hostOSName: '操作系统',
        hostOSVersion: 'v2.0',
        status: 0,
        envResourceId: '12222',
        databaseResourceList: [
            {
                id: '122222',
                serviceId: '2333',
                dbName: 'tb_user001',
                charset: 'UTF8',
                userName: '用户名',
                tablespaceName: 'apaasadm',
                tablespaceSize: '40GB',
                shardingMethod: '负载均衡',
                isDeleted: 0,
                createTime: '',
                updateTime: '',
            },
        ],
        selectedFlag: false,
        mappingId: '12.12.16-mappingId3',
        verLogicalDeploymentArchId: '12122',
        relationId: 'relationId3',
    },
]
// 弹框中可选择的资源
export const getHostList = () => [
    // {
    //     id: '11',
    //     envId: '',
    //     envName: '',
    //     softAppId: '122',
    //     softAppCode: '',
    //     isDeleted: 0,
    //     createTime: '',
    //     updateTime: '',
    //     name: 'host001',
    //     ipAddress: '12.22.120',
    //     memoryGb: '8G',
    //     cpuModel: '4G',
    //     hostOSName: '麒麟',
    //     hostOSVersion: 'v2.0',
    //     status: 0,
    //     envResourceId: '12222',
    //     fileSystems: [
    //         {
    //             id: '10',
    //             hostId: '12',
    //             mountPoint: '9.0',
    //             fsType: '',
    //             sizeGb: '10GB',
    //             uid: '',
    //             gid: '',
    //             isDeleted: 0,
    //             username: '/user01',
    //             groupName: '主组',
    //             createTime: '',
    //             updateTime: '',
    //         },
    //         {
    //             id: '1100',
    //             hostId: '1222',
    //             mountPoint: '1.0',
    //             fsType: '',
    //             sizeGb: '12GB',
    //             uid: '',
    //             gid: '',
    //             isDeleted: 0,
    //             username: 'user02',
    //             groupName: 'groupName',
    //         },
    //     ],
    //     installedSoftwares: [
    //         {
    //             id: '2323',
    //             hostId: '1212',
    //             softwareName: 'sd',
    //             version: '2.1',
    //             type: '中间件',
    //             isDeleted: 0,
    //             remark: '备注备注备注备注备注备注',
    //             createTime: '',
    //             updateTime: '',
    //         },
    //     ],
    //     selectedFlag: true,
    //     mappingId: '1222',
    //     verLogicalDeploymentArchId: '19121',
    // },
    // {
    //     id: '222222',
    //     envId: '',
    //     envName: '',
    //     softAppId: '122',
    //     softAppCode: '',
    //     isDeleted: 0,
    //     createTime: '',
    //     updateTime: '',
    //     name: 'host002',
    //     ipAddress: '12.22.130',
    //     memoryGb: '8G',
    //     cpuModel: '4G',
    //     hostOSName: '麒麟',
    //     hostOSVersion: 'v2.0',
    //     status: 0,
    //     envResourceId: '12222',
    //     fileSystems: [
    //         {
    //             id: '10',
    //             hostId: '12',
    //             mountPoint: '9.0',
    //             fsType: '',
    //             sizeGb: '10GB',
    //             uid: '',
    //             gid: '',
    //             isDeleted: 0,
    //             username: '/user01',
    //             groupName: '主组',
    //             createTime: '',
    //             updateTime: '',
    //         },
    //         {
    //             id: '1100',
    //             hostId: '1222',
    //             mountPoint: '1.0',
    //             fsType: '',
    //             sizeGb: '12GB',
    //             uid: '',
    //             gid: '',
    //             isDeleted: 0,
    //             username: 'user02',
    //             groupName: 'groupName',
    //         },
    //     ],
    //     installedSoftwares: [
    //         {
    //             id: '2323',
    //             hostId: '1212',
    //             softwareName: 'sd',
    //             version: '2.1',
    //             type: '中间件',
    //             isDeleted: 0,
    //             remark: '备注备注备注备注备注备注备注备注',
    //             createTime: '',
    //             updateTime: '',
    //         },
    //     ],
    //     selectedFlag: false,
    //     mappingId: '1222',
    //     verLogicalDeploymentArchId: '19121',
    //     relationId: 'dww',
    // },
    // {
    //     id: '33333',
    //     envId: '',
    //     envName: '',
    //     softAppId: '122',
    //     softAppCode: '',
    //     isDeleted: 0,
    //     createTime: '',
    //     updateTime: '',
    //     name: 'host003',
    //     ipAddress: '12.22.130',
    //     memoryGb: '8G',
    //     cpuModel: '4G',
    //     hostOSName: '麒麟',
    //     hostOSVersion: 'v2.0',
    //     status: 0,
    //     envResourceId: '12222',
    //     fileSystems: [
    //         {
    //             id: '10',
    //             hostId: '12',
    //             mountPoint: '9.0',
    //             fsType: '',
    //             sizeGb: '10GB',
    //             uid: '',
    //             gid: '',
    //             isDeleted: 0,
    //             username: '/user01',
    //             groupName: '主组',
    //             createTime: '',
    //             updateTime: '',
    //         },
    //         {
    //             id: '1100',
    //             hostId: '1222',
    //             mountPoint: '1.0',
    //             fsType: '',
    //             sizeGb: '12GB',
    //             uid: '',
    //             gid: '',
    //             isDeleted: 0,
    //             username: 'user02',
    //             groupName: 'groupName',
    //         },
    //     ],
    //     installedSoftwares: [
    //         {
    //             id: '2323',
    //             hostId: '1212',
    //             softwareName: 'sd',
    //             version: '2.1',
    //             type: '中间件',
    //             isDeleted: 0,
    //             remark: '备注备注备注备注备注备注备注备注',
    //             createTime: '',
    //             updateTime: '',
    //         },
    //     ],
    //     selectedFlag: false,
    //     mappingId: '1222',
    //     verLogicalDeploymentArchId: '19121',
    //     relationId: 'dww',
    // },
    {
        id: '11',
        name: 'host001',
        ipAddress: '12.22.111',
        memoryGb: '8G',
        cpuModel: '4G',
        hostOSName: '麒麟',
        hostOSVersion: 'v2.0',
        fileSystems: [
            {
                id: 0,
                mountPoint: '9.0',
                sizeGb: '10GB',
                username: '/user01',
                groupName: '主组',
            },
            {
                id: 10,
                mountPoint: '1.0',
                sizeGb: '12GB',
                username: 'user02',
                groupName: 'groupName',
            },
        ],
        installedSoftwares: [
            {
                id: 0,
                softwareName: 'sd',
                version: '2.1',
                type: '中间件',
                remark: '备注备注备注备注备注',
            },
        ],
        mappingId: null, // 映射id
        verLogicalDeploymentArchId: '21212220',
    },
    {
        id: '22',
        name: 'host002',
        ipAddress: '12.22.112',
        memoryGb: '8G',
        cpuModel: '4G',
        hostOSName: '麒麟',
        hostOSVersion: 'v21.0',
        fileSystems: [
            {
                id: 0,
                mountPoint: '9.0',
                sizeGb: '10GB',
                username: '/user01',
                groupName: '主组',
            },
            {
                id: 10,
                mountPoint: '1.0',
                sizeGb: '12GB',
                username: 'user02',
                groupName: 'groupName',
            },
        ],
        installedSoftwares: [
            {
                id: 0,
                softwareName: 'sd',
                version: '2.1',
                type: '中间件',
                remark: '备注',
            },
        ],
        mappingId: null,
        verLogicalDeploymentArchId: '21212220',
    },
    {
        id: '33',
        name: 'host003',
        ipAddress: '12.22.113',
        memoryGb: '8G',
        cpuModel: '4G',
        hostOSName: '麒麟',
        hostOSVersion: 'v21.0',
        fileSystems: [
            {
                id: 0,
                mountPoint: '9.0',
                sizeGb: '10GB',
                username: '/user01',
                groupName: '主组',
            },
            {
                id: 10,
                mountPoint: '1.0',
                sizeGb: '12GB',
                username: 'user02',
                groupName: 'groupName',
            },
        ],
        installedSoftwares: [
            {
                id: 0,
                softwareName: 'sd',
                version: '2.1',
                type: '中间件',
                remark: '备注',
            },
        ],
        mappingId: null,
        verLogicalDeploymentArchId: '21212220',
    },
]

export const getDBList = () => [
    {
        id: '9',
        envId: '12222',
        envName: '',
        softAppId: '1222244',
        softAppCode: '',
        isDeleted: 0,
        createTime: '',
        updateTime: '',
        ip: '12.12.13',
        port: '9090',
        dbType: '',
        version: '2C',
        instanceName: 'we',
        osName: '操作系统',
        osVersion: 'v2.0',
        status: 0,
        envResourceId: '122',
        databaseResourceList: [
            {
                id: '1122',
                serviceId: '23223',
                dbName: 'tb_user001',
                charset: 'UTF8',
                userName: '用户名',
                tablespaceName: 'apaasadm',
                tablespaceSize: '40GB',
                shardingMethod: '负载均衡',
                isDeleted: 0,
                createTime: '',
                updateTime: '',
            },
            {
                id: '322',
                serviceId: '23223',
                dbName: 'tb_user002',
                charset: 'UTF8',
                userName: '用户名2',
                tablespaceName: 'apaasadm2',
                tablespaceSize: '40GB',
                shardingMethod: '负载均衡2',
                isDeleted: 0,
                createTime: '',
                updateTime: '',
            },
        ],
        selectedFlag: true,
        mappingId: null,
        verLogicalDeploymentArchId: '434344',
        relationId: 'relationId1',
    },
    {
        id: '10',
        envId: '12222223333',
        envName: '',
        softAppId: '12222223333444',
        softAppCode: '',
        isDeleted: 0,
        createTime: '',
        updateTime: '',
        ip: '12.12.14',
        port: '9093',
        dbType: '',
        version: '2.1',
        instanceName: 'we',
        osName: '操作系统',
        osVersion: 'v2.0',
        status: 0,
        envResourceId: '12222',
        databaseResourceList: [
            {
                id: '122222',
                serviceId: '2333',
                dbName: 'tb_user001',
                charset: 'UTF8',
                userName: '用户名',
                tablespaceName: 'apaasadm',
                tablespaceSize: '40GB',
                shardingMethod: '负载均衡',
                isDeleted: 0,
                createTime: '',
                updateTime: '',
            },
        ],
        selectedFlag: false,
        mappingId: null,
        verLogicalDeploymentArchId: '12122',
        relationId: 'relationId2',
    },
    {
        id: '11',
        envId: '1222222333331',
        envName: '',
        softAppId: '1222222333344431',
        softAppCode: '',
        isDeleted: 0,
        createTime: '',
        updateTime: '',
        ip: '12.12.15',
        port: '9091',
        dbType: '',
        version: '2C',
        instanceName: 'we',
        osName: '操作系统',
        osVersion: 'v2.0',
        status: 0,
        envResourceId: '12222',
        databaseResourceList: [
            {
                id: '122222',
                serviceId: '2333',
                dbName: 'tb_user001',
                charset: 'UTF8',
                userName: '用户名',
                tablespaceName: 'apaasadm',
                tablespaceSize: '40GB',
                shardingMethod: '负载均衡',
                isDeleted: 0,
                createTime: '',
                updateTime: '',
            },
        ],
        selectedFlag: false,
        mappingId: null,
        verLogicalDeploymentArchId: '12122',
        relationId: 'relationId3',
    },
    {
        id: '12',
        envId: '1222222333331',
        envName: '',
        softAppId: '1222222333344431',
        softAppCode: '',
        isDeleted: 0,
        createTime: '',
        updateTime: '',
        ip: '12.12.16',
        port: '9091',
        dbType: '',
        version: '2C',
        instanceName: 'we',
        osName: '操作系统',
        osVersion: 'v2.0',
        status: 0,
        envResourceId: '12222',
        databaseResourceList: [
            {
                id: '122222',
                serviceId: '2333',
                dbName: 'tb_user001',
                charset: 'UTF8',
                userName: '用户名',
                tablespaceName: 'apaasadm',
                tablespaceSize: '40GB',
                shardingMethod: '负载均衡',
                isDeleted: 0,
                createTime: '',
                updateTime: '',
            },
        ],
        selectedFlag: false,
        mappingId: null,
        verLogicalDeploymentArchId: '12122',
        relationId: 'relationId3',
    },
]
