// mockData.ts
import { HostResourceItem, DBResourceItem } from './types'
export const getMockDetailsData = () => ({
    id: 1,
    envId: 10,
    envName: '环境标11',
    softAppId: '202020200202020202',
    softAppCode: 'APAAS.ADM',
    softAppCnName: 'APAAS.ADM',
    softAppEnName: 'datacenter',
    logicalDeploymentArchitectureId: 0,
    verLogicalDeploymentArchitectureId: 1110,
    compDeploymentList: [
        {
            path: '全行/Region/AZ/LDC/SR/CZ1',
            groupList: [
                {
                    id: 11,
                    groupName: 'NOMAL',
                    componentName: 'APAAS.AUTH.service',
                    componentVersion: '1.2.0',
                    compSpecCPU: '2核',
                    compSpecMemory: '4G',
                    compSpecInstanceNum: '2',
                    osName: '麒麟',
                    osVersion: 'v2.0',
                    hostCPU: '4核',
                    hostMemory: '8G',
                    hostInstanceNum: 2,
                    hostFileSystemList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            user: '/user1',
                            group: 'zhuzu',
                            mount: '/src/user',
                            size: '10G',
                        },
                        {
                            id: 10,
                            hostSpecId: 0,
                            user: '/user2',
                            group: 'group',
                            mount: '/src/user',
                            size: '10G',
                        },
                    ],
                    hostSoftwareList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            name: 'tomcat',
                            version: '7.8',
                            type: '客户端',
                            remark: '备注',
                        },
                    ],
                },
                {
                    id: 111,
                    groupName: 'NOMAL1',
                    componentName: 'APAAS.AUTH.service1111',
                    componentVersion: '1.2.0',
                    compSpecCPU: '2核',
                    compSpecMemory: '4G',
                    compSpecInstanceNum: '2',
                    osName: '麒麟',
                    osVersion: 'v2.0',
                    hostCPU: '4核',
                    hostMemory: '8G',
                    hostInstanceNum: 2,
                    hostFileSystemList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            user: '/user1',
                            group: 'zhuzu',
                            mount: '/src/user',
                            size: '10G',
                        },
                        {
                            id: 10,
                            hostSpecId: 0,
                            user: '/user2',
                            group: 'group',
                            mount: '/src/user',
                            size: '10G',
                        },
                    ],
                    hostSoftwareList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            name: 'tomcat',
                            version: '7.8',
                            type: '客户端',
                            remark: '备注',
                        },
                    ],
                },
            ],
        },
        {
            path: '全行/Region/AZ/LDC/SR/CZ2222',
            groupList: [
                {
                    id: 11333,
                    groupName: 'NOMAL',
                    componentName: 'APAAS.AUTH.service',
                    componentVersion: '1.2.0',
                    compSpecCPU: '2核',
                    compSpecMemory: '4G',
                    compSpecInstanceNum: '2',
                    osName: '麒麟',
                    osVersion: 'v2.0',
                    hostCPU: '4核',
                    hostMemory: '8G',
                    hostInstanceNum: 2,
                    hostFileSystemList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            user: '/user1',
                            group: 'zhuzu',
                            mount: '/src/user',
                            size: '10G',
                        },
                        {
                            id: 10,
                            hostSpecId: 0,
                            user: '/user2',
                            group: 'group',
                            mount: '/src/user',
                            size: '10G',
                        },
                    ],
                    hostSoftwareList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            name: 'tomcat',
                            version: '7.8',
                            type: '客户端',
                            remark: '备注',
                        },
                    ],
                },
                {
                    id: 11122,
                    groupName: 'NOMAL1',
                    componentName: 'APAAS.AUTH.service222',
                    componentVersion: '1.2.0',
                    compSpecCPU: '2核',
                    compSpecMemory: '4G',
                    compSpecInstanceNum: '2',
                    osName: '麒麟',
                    osVersion: 'v2.0',
                    hostCPU: '4核',
                    hostMemory: '8G',
                    hostInstanceNum: 2,
                    hostFileSystemList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            user: '/user1',
                            group: 'zhuzu',
                            mount: '/src/user',
                            size: '10G',
                        },
                        {
                            id: 10,
                            hostSpecId: 0,
                            user: '/user2',
                            group: 'group',
                            mount: '/src/user',
                            size: '10G',
                        },
                    ],
                    hostSoftwareList: [
                        {
                            id: 0,
                            hostSpecId: 0,
                            name: 'tomcat',
                            version: '7.8',
                            type: '客户端',
                            remark: '备注',
                        },
                    ],
                },
            ],
        },
    ],
    dbTypeList: [
        {
            dbType: 'TDSQL',
            dbSpecList: [
                {
                    path: '全行/Region/AZ/LDC/SR/CZ9',
                    specList: [
                        {
                            id: '122',
                            dbVersion: '7.0',
                            osSystem: 'Windows',
                            instanceName: 'instanceName990',
                            instanceNum: 3,
                            otherSpecList: [
                                {
                                    id: '1',
                                    dbName: 'db001',
                                    schemaName: 'schema001',
                                    shardingMethod: 'shardingMethod001',
                                    tablespaceName: 'tablespaceName001',
                                    tablespaceSize: '10GB',
                                    charset: 'dd',
                                    userName: 'userName001',
                                },
                                {
                                    id: '2',
                                    dbName: 'db002',
                                    schemaName: 'schema002',
                                    shardingMethod: 'shardingMethod002',
                                    tablespaceName: 'tablespaceName002',
                                    tablespaceSize: '10GB',
                                    charset: 'dd',
                                    userName: 'userName002',
                                },
                            ],
                        },
                    ],
                },
                {
                    path: '全行/Region/AZ/LDC/SR/CZ10',
                    specList: [
                        {
                            id: '1220',
                            dbVersion: '7.0',
                            osSystem: 'Windows',
                            instanceName: 'instanceName',
                            instanceNum: 3,
                            otherSpecList: [
                                {
                                    id: '1',
                                    dbName: 'db001',
                                    schemaName: 'schema001',
                                    shardingMethod: 'shardingMethod001',
                                    tablespaceName: 'tablespaceName001',
                                    tablespaceSize: '10GB',
                                    charset: 'dd',
                                    userName: 'userName001',
                                },
                                {
                                    id: '2',
                                    dbName: 'db002',
                                    schemaName: 'schema002',
                                    shardingMethod: 'shardingMethod002',
                                    tablespaceName: 'tablespaceName002',
                                    tablespaceSize: '10GB',
                                    charset: 'dd',
                                    userName: 'userName002',
                                },
                            ],
                        },
                    ],
                },
            ],
        },
    ],
})

export const getMockHostResourceItems = (): HostResourceItem[] => [
    {
        id: 1111111222222,
        name: 'host001',
        ipAddress: '12.22.110',
        memoryGb: '8G',
        cpuModel: '4G',
        osName: '麒麟',
        osVersion: 'v2.0',
        fileSystems: [
            {
                id: 0,
                mountPoint: '9.0',
                sizeGb: '10GB',
                username: '/user01',
                groupName: '主组',
            },
            {
                id: 10,
                mountPoint: '1.0',
                sizeGb: '12GB',
                username: 'user02',
                groupName: 'groupName',
            },
        ],
        installedSoftwares: [
            {
                id: 0,
                softwareName: 'sd',
                version: '2.1',
                type: '中间件',
                remark: '备注',
            },
        ],
        mappingId: '111111110',
        verLogicalDeploymentArchId: '21212220',
    },
]

export const getMockDBResources = (): DBResourceItem[] => [
    {
        id: '11111',
        ip: '12.12.12',
        port: '9090',
        version: '2C',
        instanceName: 'we',
        osName: '操作系统',
        osVersion: 'v2.0',
        databaseResourceList: [
            {
                id: 0,
                dbName: 'tb_user001',
                charset: 'UTF8',
                userName: '用户名',
                tablespaceName: 'apaasadm',
                tablespaceSize: '40GB',
                shardingMethod: '负载均衡',
            },
        ],
        mappingId: '909090',
        verLogicalDeploymentArchId: '23333',
    },
]

export const getHostResourceEdit = () => [
    {
        id: '1111111222222',
        envId: '',
        envName: '',
        softAppId: '122',
        softAppCode: '',
        isDeleted: 0,
        createTime: '',
        updateTime: '',
        name: 'host001',
        ipAddress: '12.22.120',
        memoryGb: '8G',
        cpuModel: '4G',
        osName: '麒麟',
        osVersion: 'v2.0',
        status: 0,
        envResourceId: '12222',
        fileSystems: [
            {
                id: '10',
                hostId: '12',
                mountPoint: '9.0',
                fsType: '',
                sizeGb: '10GB',
                uid: '',
                gid: '',
                isDeleted: 0,
                username: '/user01',
                groupName: '主组',
                createTime: '',
                updateTime: '',
            },
            {
                id: '1100',
                hostId: '1222',
                mountPoint: '1.0',
                fsType: '',
                sizeGb: '12GB',
                uid: '',
                gid: '',
                isDeleted: 0,
                username: 'user02',
                groupName: 'groupName',
            },
        ],
        installedSoftwares: [
            {
                id: '2323',
                hostId: '1212',
                softwareName: 'sd',
                version: '2.1',
                type: '中间件',
                isDeleted: 0,
                remark: '备注',
                createTime: '',
                updateTime: '',
            },
        ],
        selectedFlag: true,
        mappingId: '1222',
        verLogicalDeploymentArchId: '19121',
    },
    {
        id: '222222',
        envId: '',
        envName: '',
        softAppId: '122',
        softAppCode: '',
        isDeleted: 0,
        createTime: '',
        updateTime: '',
        name: 'host002',
        ipAddress: '12.22.130',
        memoryGb: '8G',
        cpuModel: '4G',
        osName: '麒麟',
        osVersion: 'v2.0',
        status: 0,
        envResourceId: '12222',
        fileSystems: [
            {
                id: '10',
                hostId: '12',
                mountPoint: '9.0',
                fsType: '',
                sizeGb: '10GB',
                uid: '',
                gid: '',
                isDeleted: 0,
                username: '/user01',
                groupName: '主组',
                createTime: '',
                updateTime: '',
            },
            {
                id: '1100',
                hostId: '1222',
                mountPoint: '1.0',
                fsType: '',
                sizeGb: '12GB',
                uid: '',
                gid: '',
                isDeleted: 0,
                username: 'user02',
                groupName: 'groupName',
            },
        ],
        installedSoftwares: [
            {
                id: '2323',
                hostId: '1212',
                softwareName: 'sd',
                version: '2.1',
                type: '中间件',
                isDeleted: 0,
                remark: '备注',
                createTime: '',
                updateTime: '',
            },
        ],
        selectedFlag: false,
        mappingId: '1222',
        verLogicalDeploymentArchId: '19121',
        relationId: 'dww',
    },
]

export const getDBResourceEdit = () => [
    {
        id: '9',
        envId: '12222',
        envName: '',
        softAppId: '1222244',
        softAppCode: '',
        isDeleted: 0,
        createTime: '',
        updateTime: '',
        ip: '12.12.13',
        port: '9090',
        dbType: '',
        version: '2C',
        instanceName: 'we',
        osName: '操作系统',
        osVersion: 'v2.0',
        status: 0,
        envResourceId: '122',
        databaseResourceList: [
            {
                id: '1122',
                serviceId: '23223',
                dbName: 'tb_user001',
                charset: 'UTF8',
                userName: '用户名',
                tablespaceName: 'apaasadm',
                tablespaceSize: '40GB',
                shardingMethod: '负载均衡',
                isDeleted: 0,
                createTime: '',
                updateTime: '',
            },
            {
                id: '322',
                serviceId: '23223',
                dbName: 'tb_user002',
                charset: 'UTF8',
                userName: '用户名2',
                tablespaceName: 'apaasadm2',
                tablespaceSize: '40GB',
                shardingMethod: '负载均衡2',
                isDeleted: 0,
                createTime: '',
                updateTime: '',
            },
        ],
        selectedFlag: true,
        mappingId: '343434',
        verLogicalDeploymentArchId: '434344',
        relationId: 'relationId1',
    },
    {
        id: '10',
        envId: '12222223333',
        envName: '',
        softAppId: '12222223333444',
        softAppCode: '',
        isDeleted: 0,
        createTime: '',
        updateTime: '',
        ip: '12.12.14',
        port: '9093',
        dbType: '',
        version: '2C',
        instanceName: 'we',
        osName: '操作系统',
        osVersion: 'v2.0',
        status: 0,
        envResourceId: '12222',
        databaseResourceList: [
            {
                id: '122222',
                serviceId: '2333',
                dbName: 'tb_user001',
                charset: 'UTF8',
                userName: '用户名',
                tablespaceName: 'apaasadm',
                tablespaceSize: '40GB',
                shardingMethod: '负载均衡',
                isDeleted: 0,
                createTime: '',
                updateTime: '',
            },
        ],
        selectedFlag: false,
        mappingId: '23444',
        verLogicalDeploymentArchId: '12122',
        relationId: 'relationId2',
    },
    {
        id: '101',
        envId: '1222222333331',
        envName: '',
        softAppId: '1222222333344431',
        softAppCode: '',
        isDeleted: 0,
        createTime: '',
        updateTime: '',
        ip: '12.12.15',
        port: '9091',
        dbType: '',
        version: '2C',
        instanceName: 'we',
        osName: '操作系统',
        osVersion: 'v2.0',
        status: 0,
        envResourceId: '12222',
        databaseResourceList: [
            {
                id: '122222',
                serviceId: '2333',
                dbName: 'tb_user001',
                charset: 'UTF8',
                userName: '用户名',
                tablespaceName: 'apaasadm',
                tablespaceSize: '40GB',
                shardingMethod: '负载均衡',
                isDeleted: 0,
                createTime: '',
                updateTime: '',
            },
        ],
        selectedFlag: false,
        mappingId: '23444',
        verLogicalDeploymentArchId: '12122',
        relationId: 'relationId3',
    },
]
